### ISSUE TITLE
Could not load file or assembly 'BouncyCastle.Crypto, Version=1.7.4114.6375

### ISSUE THREAD

**Issue by GaaTY** [bitpay/csharp-bitpay-client#25]
See my comment in issue #20 

I followed the steps and solutions provided, but still getting the same errors.

**Comment by MrTarantula** [comment]
If you're still having issues, you can try my depends branch https://github.com/mrtarantula/csharp-bitpay-client/tree/depends. All I did was switch from the hardcoded dependencies to the latest nuget versions. I've submitted a PR to bitpay.

**Comment by pieterpoorthuis** [comment]
Thanks a lot, I've merged your pull requests

**Comment by MrTarantula** [comment]
Could you also update the package on Nuget? It's still broken and very old there.
